name: Maven Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Set up Maven settings
      run: |
        echo "<settings>" > ${{ github.workspace }}/settings.xml
        echo "  <servers>" >> ${{ github.workspace }}/settings.xml
        echo "    <server>" >> ${{ github.workspace }}/settings.xml
        echo "      <id>github</id>" >> ${{ github.workspace }}/settings.xml
        echo "      <username>${{ github.actor }}</username>" >> ${{ github.workspace }}/settings.xml
        echo "      <password>${{ secrets.GITHUB_TOKEN }}</password>" >> ${{ github.workspace }}/settings.xml
        echo "    </server>" >> ${{ github.workspace }}/settings.xml
        echo "  </servers>" >> ${{ github.workspace }}/settings.xml
        echo "</settings>" >> ${{ github.workspace }}/settings.xml

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Publish to GitHub Packages
      run: mvn deploy -s ${{ github.workspace }}/settings.xml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
